export const works = [
    {
        id: 0,
        title: 'Administrative employee',
        date: '2013 - 2014',
        company: 'National Technological University',
        place: 'Buenos Aires, Argentina',
        description: 'I worked in AFA Plus, the security project of the Argentine Football Association (AFA) and the National Technological University (UTN), taking fingerprints and entering the data of the fans so that they can enter the stadiums in Argentina.',
    },
    {
        id: 1,
        title: 'Administrative employee - Frontend developer',
        date: '2014 - 2021',
        company: 'University of Buenos Aires',
        place: 'Buenos Aires, Argentina',
        description: 'I worked as an administrative employee at the University of Buenos Aires for two years. Then from 2016 I was the operator of the GEDO, GDE and Comdoc systems and in 2021 I worked for six months on the website of the scholarship office as a frontend developer.',
    },
    {
        id: 2,
        title: 'Author - Writer',
        date: '2016 - 2020',
        company: 'Antrophistoria',
        place: 'Madrid, Spain - Remote',
        description: 'Writer of anthropological articles in Spanish language on a freelance basis.',
    },
    {
        id: 3,
        title: 'Technical Service',
        date: '2022 - 2023',
        company: 'Sitel - PlayStation',
        place: 'Berlin, Germany - Remote',
        description: "Technical support in Hardware and Network accounts for PlayStation's project.",
    },
    {
        id: 4,
        title: 'Frontend developer',
        date: '2020 - to date',
        company: 'Freelance',
        place: 'Remote',
        description: 'I develop web apps in React with a backend colleague. Some clients: One to One Trade Consulting (USA), Romar Group (Argentina), Cereals Online (Argentina), Inter Ibiza (Spain), C.D. Manchego (Spain).',
    },
    {
        id: 5,
        title: 'React frontend developer',
        date: '2023 - to date',
        company: 'AFEC Football Academy',
        place: 'Madrid, Spain - Remote',
        description: 'I work developing new tools for AFEC Football Academy as a front end developer with React, as well as on jQuery to React migration of the main website.',
    },
]